# Generated by Django 3.1.6 on 2022-12-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balancedays', models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Leave days per year counter')),
                ('leaves', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.leave')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
