# Generated by Django 3.1.6 on 2022-10-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20221003_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='balancedays',
            field=models.PositiveIntegerField(default=30, verbose_name='Leave days per year counter'),
        ),
    ]
