# Generated by Django 3.1.6 on 2022-12-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('leave', '0002_balanceleave'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BalanceLeave',
            new_name='BalanceLeaves',
        ),
    ]
