# Generated by Django 3.1.6 on 2022-12-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20221220_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceleaves',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
