# Generated by Django 3.1.6 on 2022-11-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20221017_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='balancedays',
            field=models.PositiveIntegerField(verbose_name='Leave days per year counter'),
        ),
    ]
