# Generated by Django 3.1.6 on 2022-11-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20221101_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='balancedays',
            field=models.PositiveIntegerField(default=10, verbose_name='Leave days per year counter'),
        ),
    ]
