# Generated by Django 3.1.6 on 2022-11-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_company_companystaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companystaff',
            name='_id',
        ),
        migrations.AddField(
            model_name='companystaff',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companystaff',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
