# Generated by Django 3.1.6 on 2022-11-07 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20221107_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companystaff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companystaff',
            name='password',
        ),
        migrations.AddField(
            model_name='companystaff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
