# Generated by Django 3.1.6 on 2022-11-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
