# Generated by Django 3.1.6 on 2022-11-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20221108_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companystaff',
            name='user',
        ),
        migrations.AddField(
            model_name='companystaff',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='companystaff',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
