# Generated by Django 3.1.6 on 2022-11-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20221109_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_company_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='companystaff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companystaff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='companystaff',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
