# Generated by Django 3.1.6 on 2022-11-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20221109_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystaff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
    ]
