# Generated by Django 3.1.6 on 2022-11-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20221111_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystaff',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
