# Generated by Django 3.1.6 on 2022-11-16 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_companystaff_is_authenticated'),
        ('management', '0002_invoice_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
