# Generated by Django 3.1.6 on 2022-11-11 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20221111_1626'),
        ('administration', '0002_auto_20221107_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AlterField(
            model_name='task',
            name='company',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
