# Generated by Django 3.1.6 on 2022-11-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_companystaff_is_authenticated'),
        ('administration', '0003_auto_20221111_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='company',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
