# Generated by Django 3.1.6 on 2022-12-14 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_companystaff_is_authenticated'),
        ('administration', '0004_auto_20221116_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
