# Generated by Django 3.1.6 on 2022-10-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50, null=True),
        ),
    ]
