# Generated by Django 3.1.6 on 2022-12-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
        ('manager_leave', '0002_balanceleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceleave',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.manager'),
        ),
    ]
