# Generated by Django 3.1.6 on 2022-12-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_leave', '0003_balanceleave_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceleave',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
