# Generated by Django 3.1.6 on 2022-12-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_leave', '0004_balanceleave_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerleave',
            name='balancedays',
        ),
        migrations.RemoveField(
            model_name='managerleave',
            name='defaultdays',
        ),
    ]
