# Generated by Django 3.1.6 on 2022-10-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(help_text='resign start date is on ..', null=True, verbose_name='Start Date')),
                ('reason', models.CharField(blank=True, help_text='add additional information for resign', max_length=255, null=True, verbose_name='Reason for Resignation')),
                ('status', models.CharField(default='pending', max_length=12)),
                ('is_approved', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assigned_too', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_assigned_too', to='managers.manager')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Resign',
                'verbose_name_plural': 'Resigns',
                'ordering': ['-created'],
            },
        ),
    ]
